### ISSUE TITLE
`TAPi18n.__` not working when being called from a package

### ISSUE THREAD

**Issue by hitchcott** [TAPevents/tap-i18n#100]
Weird one, and I could be missing a step, but I can't figure this one out.

I want to use `TAPi18n.__` on the client side, but within a package, as part of, say, a helper. `{{_ 'key'}}` is working as expected in package templates, but `TAPi18n.__` is not working in methods.

Reproduction here: https://github.com/hitchcott/tap-i18n-issue-100. It's a shell project with a `dummy:package`, illustrating the problem.

**Comment by theosp** [comment]
Within a package, `__` should be used and not `TAPi18n.__` (package templates are wired to `__`). See:
https://github.com/TAPevents/tap-i18n#package-level-tap-i18n-functions

**Comment by stivaugoin** [comment]
How it's work?
`__("key")` ?
I have this error: `Exception in template helper: ReferenceError: __ is not defined`

**Comment by nicooprat** [comment]
@stivaugoin Just tried it and it worked: `__('story.fields.remove.confirm')`. Are you sure you're using this function within a package ?

**Comment by stivaugoin** [comment]
Works fine, my bad. Wrong version!
