### ISSUE TITLE
Meteor v1.2: "to: wrong arguments" and "toEnd: wrong arguments" errors on startup

### ISSUE THREAD

**Issue by brianlukoff** [TAPevents/tap-i18n#104]
In Meteor 1.2-rc7, I'm getting the following errors on startup during the tap-i18n-compiler step:

    => Started proxy.
    => Started MongoDB.
    to: wrong argumentstap-i18n-compiler` fr...  |

    toEnd: wrong arguments

**Comment by mquandalle** [comment]
:+1:

**Comment by theosp** [comment]
https://github.com/wekan/wekan/issues/264 related.

**Comment by theosp** [comment]
Thanks for reporting this guys. As it seems we still have time till "late summer", the current release date for v1.2, I tend to wait with investing time to investigate this issue, might be solved in future RCs.

**Comment by brianlukoff** [comment]
After some digging, it appears to be an issue with Shell.js (https://github.com/arturadib/shelljs/issues/159) which I think is now used by Meteor.  The issue crops up when String.js (which simple-schema uses) tries to access all methods of String.

**Comment by mquandalle** [comment]
Is MDG aware of the issue?

**Comment by brianlukoff** [comment]
Just filed https://github.com/meteor/meteor/issues/5107.

**Comment by mquandalle** [comment]
This is fixed in Meteor `1.2-rc.14`. Thank you very much @brianlukoff for identifying and reporting this bug to MDG :-)

**Comment by brianlukoff** [comment]
Great - happy to help!

**Comment by obiwarn** [comment]
reappears in 1.3 - beta 11
