### ISSUE TITLE
Adding package-tap.i18n prehibits Meteor startup

### ISSUE THREAD

**Issue by derwaldgeist** [TAPevents/tap-i18n#105]
I am trying to follow the instructions for package developers. However, as soon as I add the following line to my package.js file, the app crashes:

``` js
api.addFiles("package-tap.i18n", ["client", "server"]);
```

Although I don't see any exception in the server logs, the Meteor application does not startup in the browser anymore. In the browser's console, I only see error messages that Meteor's objects like "Meteor", "Tracker" or "Session" are not available.

If I omit the line, everything works again.

My package-tap.i18n file is as follows:

``` js
{
  "namespace": "project"
}
```

The documentation also refers to an option `languages_files_dir` by stating:

```
Should be the same path as languages_files_dir option above
```

But I cannot find an explanation of this option "above". Maybe the docs require an update?

**Comment by nicooprat** [comment]
I'm having some issues like yours at the moment (using Meteor 1.3 beta 8, don't know if any link with this):

````
package-tap.i18n should be loaded before languages files (*.i18n.json)
````

**Comment by GongT** [comment]
```
=> Errors prevented startup:

   While building the application:
   /data/web/test/package-tap.i18n: package-tap.i18n should be loaded before
   languages files (*.i18n.json)

=> Your application has errors. Waiting for file change.
```

**Comment by zhaoyao91** [comment]
+1
    
W20160524-16:34:45.731(8)? (STDERR) Error: package-tap.i18n should be loaded before languages files (*.i18n.json)
W20160524-16:34:45.731(8)? (STDERR)     at _ (home/theosp/tap-i18n/unittest/test-packages/blank-package-tap-i18n/package-tap.i18n:1:1)
W20160524-16:34:45.731(8)? (STDERR)     at home/theosp/tap-i18n/unittest/test-packages/blank-package-tap-i18n/package-tap.i18n:1:1
W20160524-16:34:45.731(8)? (STDERR)     at packages/tap_i18n/packages/tap_i18nunittest/test-packages/project-with-translation-files-under-server-dir-SHOULD-FAIL/server/file2.en.i18n.json:12:1
W20160524-16:34:45.731(8)? (STDERR)     at C:\Users\zhaoyao\Desktop\Archinvite\app\.meteor\local\build\programs\server\boot.js:283:10
W20160524-16:34:45.731(8)? (STDERR)     at Array.forEach (native)
W20160524-16:34:45.731(8)? (STDERR)     at Function._.each._.forEach (C:\Users\zhaoyao\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160524-16:34:45.731(8)? (STDERR)     at C:\Users\zhaoyao\Desktop\Archinvite\app\.meteor\local\build\programs\server\boot.js:133:5

**Comment by geedmo** [comment]
+1
Meteor 1.3.2.4

**Comment by theosp** [comment]
Hi guys,

Sorry about that, revert temporarily to 1.8.0.

I will fix it in the following hours.

-Daniel

**Comment by zhaoyao91** [comment]
I am pushed to have finished a new i18n package...

**Comment by theosp** [comment]
Please read my comment here: https://github.com/TAPevents/tap-i18n/issues/169#issuecomment-221282903

**Comment by c9s** [comment]
+1
