### ISSUE TITLE
Plugin.registerSourceHandler does not recognize files with filename === fileExtention (since meteor@1.2)

### ISSUE THREAD

**Issue by lucendio** [TAPevents/tap-i18n#113]
Hi,

I updated one of my project (in which I defined a custom ``helper_name`` in ``project-tap.i18n``) to meteor@1.2 and ``tap:i18n@1.6.1``. After that the client throws an error about the custom template helper were not defined. After some time of debugging your package I found out that files with a ``filename === fileExtention`` were not recognized by the handler. After renaming ``project-tap.i18n`` to ``STRING.project-tap.i18n`` everything worked fine again. [This seems to be intended/previouse bug by MDG](https://github.com/meteor/meteor/issues/3985). A solution was mentioned by dglasser at the end of that issue.

**Comment by mikeifomin** [comment]
@lucendio thank You!

You've save a lot of my time :+1:

**Comment by JeremySaks** [comment]
:+1: great tip. wasn't sure what was going on until i prefixed `project-tap.i18n`

**Comment by hitchcott** [comment]
Can confirm this issue. `project.tap-i18n` is no longer supported by meteor - use `my.project.tap-i18n` to get it working for now.

@theosp - I guess we just update the docs in the meantime?

**Comment by theosp** [comment]
Fixed on v1.7.

Please don't use prefixes, only the exact match will be recognized.

I haven't pushed v1.7 to atmosphere yet, you can pull it from this rep.

Will be published to atmosphere after testing on v1.1 .

-Daniel

**Comment by theosp** [comment]
v1.7 published
