### ISSUE TITLE
Error when trying to translate Simple-Schema fields

### ISSUE THREAD

**Issue by ziedmahdi** [TAPevents/tap-i18n#116]
I am trying to use tap-i18n to translate firstOption in a schema definition. Here is the code:

```
LanguageOptions = { 
    lng: 'fr'
};

ActionSchema = new SimpleSchema({
    type: {
         type: String,        
         autoform: {
             afFieldInput: {
                 firstOption: TAPi18n.__("select_an_option", LanguageOptions)           
             },
    }
}
```

And this is the given error:
I20151008-16:36:59.521(0)? 
W20151008-16:36:59.530(0)? (STDERR) 
W20151008-16:36:59.530(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151008-16:36:59.531(0)? (STDERR)                                             throw(ex);
W20151008-16:36:59.531(0)? (STDERR)                                                   ^
W20151008-16:36:59.588(0)? (STDERR) TypeError: Object #<Object> has no method 'en'
W20151008-16:36:59.588(0)? (STDERR)     at [object Object].__ (packages/tap:i18n/lib/tap_i18n/tap_i18n-server.coffee:26:16)
W20151008-16:36:59.588(0)? (STDERR)     at app/lib/ads.js:16:38
W20151008-16:36:59.588(0)? (STDERR)     at app/lib/ads.js:203:3
W20151008-16:36:59.588(0)? (STDERR)     at /home/ubuntu/workspace/.meteor/local/build/programs/server/boot.js:222:10
W20151008-16:36:59.589(0)? (STDERR)     at Array.forEach (native)
W20151008-16:36:59.589(0)? (STDERR)     at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151008-16:36:59.589(0)? (STDERR)     at /home/ubuntu/workspace/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

I don't know if this error is related to pre `Meteor.startup()` or not. According to the changelog, the pre `Meteor.startup()` has been fixed since version 1.5.0

I created a simple app to reproduce the error.
this is the repository link: 
https://github.com/ziedmahdi/test-tapi18n

Thank you very much for your help

**Comment by rijk** [comment]
Possibly related to #123
