### ISSUE TITLE
Not working with meteor and angular in .ng.html files

### ISSUE THREAD

**Issue by damirkusar** [TAPevents/tap-i18n#118]
Hi, 

just wanted to use this package in meteor with angular. But it works just in non ".ng.html" files, so it is not compatible with Angular. Is there a way to make this work, since I have just one file which has no .ng.html extension and this is the main index :)

Thanks and BR
Damir

**Comment by damirkusar** [comment]
Hi Guys,

any news / updates / comments on the issue?

**Comment by yobre** [comment]
I'm in the same situation.
Is possible to change the helper " _ " with a filter like [angular-translate](https://github.com/angular-translate/angular-translate)? e.g. {{ "hello" | tapI18n }}

i'm using [angular-meteor](http://www.angular-meteor.com/)

Thanks
