### ISSUE TITLE
Nested values don't work

### ISSUE THREAD

**Issue by Pagebakers** [TAPevents/tap-i18n#119]
Unlike documented in i18next, I can't get nested values to work. Isn't the following supported with tapi18n?

``` javascript
{  key: '__person.name.first__ is important' } }

TAPi18n.t("key", { person: { name: { first: 'cristina' } } });
// nothing happens, the key isn't replaced.
```

I tried the same with sprintf, like this:

``` javascript
{key2: 'Hello %(users[0].name)s, %(users[1].name)s and %(users[2].name)s'}
// tapi18n throws `[sprintf] huh?`
```

**Comment by in0ni** [comment]
It would be great to know if this feature is; not supported, requires different syntax, or this is a bug...
I also cannot get this working with a simpler example that matches [i18next documentation](http://i18next.github.io/i18next/pages/doc_features.html):

json file:
`{
  "nested": "1 $t(nesting2)",
  "nested2": "2 $t(nested3)",
  "nested3": "3"
}`

template:
`{{_ 'nested'}}`
