### ISSUE TITLE
know when language has finished changing

### ISSUE THREAD

**Issue by Cerealkillerway** [TAPevents/tap-i18n#120]
when I change the language, the new language is not available immediatly;
in most cases is not a prolem since i18n strings are updated reactively; but for example, if I have to start an external plugin using the current language just setted, it starts with the old language:

```
     TAPi18n.setLanguage('it');
     console.log(TAPi18n.getLanguage());          // -> en!!!!!!!!!!

     //starting a plugin here, using TAPi18n.getLanguage() to know the language to use for it, will not work

     setTimeout(function() {
         console.log(TAPi18n.getLanguage());     // -> it
     }, 2000);
```

is there a way to know when language has finished changing?

**Comment by janat08** [comment]
it says to invalidate it- computation-, and i don't know what to do with that

**Comment by maxnowack** [comment]
I've got the same issue. Any updates on this?

**Comment by janat08** [comment]
I think I used event for changing language instead of repo API.
