### ISSUE TITLE
Meteor Tabular Columns + i18n = Crash

### ISSUE THREAD

**Issue by VansonLeung** [TAPevents/tap-i18n#123]
Hi,

So I'm having a few problems when using the JS call to set the titles of the columns in aldeed:meteor-tabular.

I'm calling it this way,

```
TAPi18n.__('name')
```

And this is the error that I'm receiving.

```
TypeError: Object [object Object] has no method 'en'
    at Object.__ (packages/tap_i18n/packages/tap_i18n.js:2989:1)
    at collections.js:64:35
    at /Users/Vanson/Documents/Vanson/Projects/mrchin_barmap/codes/backend/barmap_cms/.meteor/local/build/programs/server/app/collections.js:111:4
    at /Users/Vanson/Documents/Vanson/Projects/mrchin_barmap/codes/backend/barmap_cms/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Vanson/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/Vanson/Documents/Vanson/Projects/mrchin_barmap/codes/backend/barmap_cms/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by rijk** [comment]
I have the same issue, was just about to post it. The error is on line https://github.com/TAPevents/tap-i18n/blob/master/lib/tap_i18n/tap_i18n-server.coffee#L26. I have no idea how to fix. `aldeed:tabular` requires the translation to happen on the backend, so there is no way around this unfortunately.

**Comment by rijk** [comment]
@theosp sorry to spam, but could you check this one out?

**Comment by theosp** [comment]
Hi Rijk I am in a quite busy period, if you can prepare the bare minimum
Meteor project in which this problem occurs and push to github, I'll do my
best to check it promptly.

Thanks,
-Daniel
