### ISSUE TITLE
multiple plural forms not supported?

### ISSUE THREAD

**Issue by thewaywest** [TAPevents/tap-i18n#125]
I am trying to use the documented i18next() feature that forks single/plural based on varying levels of count. (_see: http://i18next.com/pages/doc_features.html @ Multiple Plural Forms_). My JSON includes the following:

> {
>    "Title": "One Item",
>    "Title_plural_0": "No Items",
>    "Title_plural_2": "Two Items",
>    "Title_plural_3": "A Few Items [%s]",
>    "Title_plural_9": "Many Items [%s]"
> }

I am calling this from a template with the following line, where _itemcount_ is a template helper that returns the number of items in the returned document set: 

> {{_ "Title" itemcount count=itemcount}}

The translation only seems to work with simple singular/plural definitions. In the example above, I get the "Title" definition, independent of the number of items actually returned. Adding a plural JSON entry like the one below returns the correct plural text for any value > 1, as well as the correct value returned using itemcount:

> {
>    "Title": "One Item",
>    "Title_plural": "%s Items"
> }

Since tap-i18n uses "count=_n_" instead of the i18next "{ count: _n_ }" format, I am thinking this might not be implemented, or that I need a workaround to correctly access the underlying library. Can't find it googling or in documentation.

Help?

**Comment by dasdeck** [comment]
Just waht I was thinking. I think the "zero" case is a must have!

Cheers!

JM

**Comment by ciro207** [comment]
I was searching for the same thing, but I cannot find any solution yet.
Any update here?

**Comment by kachkaev** [comment]
+

**Comment by theosp** [comment]
i18next v1.11 don't have complete rules to all languages.

You'll have to clone this rep into your packages folder and add the rule for zero here:
https://github.com/TAPevents/tap-i18n/blob/master/lib/tap_i18next/tap_i18next-1.7.3.js#L1490

If you have an overall solution, please send PR.

Thanks

**Comment by thewaywest** [comment]
Thanks for reviewing this issue, theosp. I'll look into the way TAP has implemented this -- maybe there is a workaround available. At first glance, it looks as though a generalized and coded solution (in the i18n package) is being limited by the coded plurals in the section you highlighted for us. I was expecting more of a "pass-through" framework, where the JSON outlined above would allow me to supply plural forms myself, without them being enumerated in TAP directly. 

Could you explain in a few words how that section of TAP code is intended to work? IT would help me avoid extra effort building (or rebuilding) an "any plurals" solution.

Many thanks!

**Comment by theosp** [comment]
The highlighted code isn't mine (3rd party lib), so, just like you I'll
have to study it to come up with solution.

-Daniel

**Comment by thewaywest** [comment]
I see, thank you. 

It looks as though it needs to return something for "0", and for almost all languages that line is not present. Arabic would appear to handle this correctly:

            "ar": {
                "name": "Arabic", 
                "numbers": [
                    0, 
                    1, 
                    2, 
                    3, 
                    11, 
                    100
                ], 
                "plurals": function(n) { return Number(n===0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5); }
            }, 

While English does not:

            "en": {
                "name": "English", 
                "numbers": [
                    1, 
                    2
                ], 
                "plurals": function(n) { return Number(n != 1); }
            }, 

I don't have time to meddle with that code at the moment, but it would seem that if languages include a zero-case, the rest might flow correctly. English would be rewritten as such:

            "en": {
                "name": "English", 
                "numbers": [
                    0, 
                    1, 
                    2
                ], 
                "plurals": function(n) { return Number(n===0 ? 0 : n==1 ? 1 : 2 ); }
            }, 

There is probably a more generalized function that will be more efficient and look similar across languages. This is 3rd party but hard-coded into TAP, correct? I could send a rewrite for your testing if helpful...

**Comment by thewaywest** [comment]
... and actually, I hadn't expected the plural forms would be handled for me anyway, and would prefer to control them myself in the localized JSON (as described in the lead question). Is it possible to simply discard the 3rd party code (which is incomplete as it stands), or provide a workaround option for us? Thanks again for thinking about this.

**Comment by poussik** [comment]
Late answer, but I have a working solution without fork.

In **both** client/server side, you can add a rule directly to i18next:
```javascript
TAPi18next.pluralExtensions.addRule("en", {
    "name": "English",
    "numbers": [ 0, 1, 2 ],
    "plurals": function(n) {
        return Number(n === 0 ? 0 : n === 1 ? 1 : 2);
    }
});
```

Then in the i18n files:
```yaml
nb_jobs_running: "One job is running"
nb_jobs_running_plural_0: "No running job"
nb_jobs_running_plural: "__count__ jobs are running"
```

At this stage, it works **only** after a language switch, not when the page is loaded.
Calling TAPi18next.pluralExtensions.setCurrentLng explicitely after Meteor.startup seems to fix this issue.
