### ISSUE TITLE
Language files in Packages not updated until namespace is changed.

### ISSUE THREAD

**Issue by DavidSichau** [TAPevents/tap-i18n#128]
I had an very strange issue. If you update an language file inside an package, e.g. add a new string. The delivered language files are not updated. Only if the `namespace` variable inside the package is renamed the language files delivered gets updated.

**Comment by smeijer** [comment]
Can this be a caching issue? I'm also experiencing this, my workaround for now is to update the package version number. But during development this is really frustrating.

**Comment by DavidSichau** [comment]
I played around some while. It seems to be a caching issue. If I rename the namespace it works perfect. But as soon as I go back to the old one it reverts to a changed version. It seems that the language json files are not regenerated on a new build.

**Comment by AnthonyReid99** [comment]
I can confirm this as well. I can also get it to refresh by adding or removing a newline from my language file.

**Comment by kahmali** [comment]
To piggyback on what @AnthonyReid99 said, it appears to only refresh locally when changing a line in the language file. From my manual testing, that hack doesn't seem to work reliably when deploying to a server. What version of Meteor are other folks on? We're on 1.2.1.

**Comment by DavidSichau** [comment]
Locally I also can force the new language file to reload by making chances. However for the deployment this does not help. I also use Meteor 1.2.1

**Comment by berkaey** [comment]
+1

**Comment by berkaey** [comment]
I notice that beside english "en" the new namespaces wont reach to deployement even if I change the version of the package. do you know any action just the flush cache/old json files?

**Comment by berkaey** [comment]
any update on this? @theosp ?

**Comment by alexcorre** [comment]
+1

**Comment by abhiaiyer91** [comment]
+1 could use a response on this. Or guidance on what the issue is so we can fix it

**Comment by luixal** [comment]
Could someone that manage to make an i18n package work withing a project point me to a working example?

I'm trying to keep all my i18n stuff work as a package for my main project but can't make it work...
