### ISSUE TITLE
How to best set the language on startup, based on the user preferences?

### ISSUE THREAD

**Issue by derwaldgeist** [TAPevents/tap-i18n#131]
I am struggling with setting the language based on a user preference. It works if I hook into Accounts.onLogin() and set the language if the user logs in, based on a language setting I defined in the user's profile.

But this only works if the user logs in via a login dialog. It does not work if the user is transparently logged in, based on a login token.

To workaround this, I tried to check Meteor.user() in a Tracker.autorun(), and - once it changes - call TAPi18n.setLanguage() accordingly. But this does not work reliably. Sometimes, the language is set correctly, sometimes the language falls back to "en", although I pass the right language to the setLanguage() method.

If I inspect the TAPi18n object, in any of these cases the loadedLanguages property correctly shows both languages. But interestingly, in the cases where the language is set correctly, my preferred language ("de" in my case) shows up twice. In the cases where the language falls back to English, it only shows up once.

Are there any "best practices" available to set the language on app startup?

**Comment by LukasHavemann** [comment]
+1
