### ISSUE TITLE
Using i18next.t(key, options) proxy not working

### ISSUE THREAD

**Issue by netpoe** [TAPevents/tap-i18n#134]
The TAPi18n.__ specify to look after the i18next.t documentation to expand on how to use the function.

I have implemented the function successfully with simple messages, but when it comes to interpolation, I've tried these two alternatives and none of them work: 

``` javascript
// Using %s interpolation
TAPi18n.__("campaign-exists", 
    error['reason']['profileName'], 
    error['reason']['campaignState'],
    error['reason']['campaignCountry'],
    error['reason']['campaignId'],
    error['reason']['campaignURL']);

"campaign-exists": "There's already a campaign for %s in %s, %s <a href='/campaigns/%s/%s' class='underline'>click here</a> to back and share this campaign."

// Usign i18next.t interpolation style:
TAPi18n.__("campaign-exists", {
    profileName: error['reason']['profileName'], 
    campaignState: error['reason']['campaignState'],
    campaignCountry: error['reason']['campaignCountry'],
    campaignId: error['reason']['campaignId'],
    campaignURL: error['reason']['campaignURL']),
});

"campaign-exists": "There's already a campaign for {{profileName}} in {{campaignState}}, {{campaignCountry}} <a href='/campaigns/{{campaignId}}/{{campaignURL}}' class='underline'>click here</a> to back and share this campaign."
```

**Comment by TimoRuetten** [comment]
+1 I have the same problem currently. Would be nice to get a hin

**Comment by theosp** [comment]
Please refer to v1.11 of i18next and let me know if issue remains:

http://i18next.github.io/i18next/pages/doc_features.html

I'll add a comment to readme that tap:i18n is based on v1.11 of i18next (v2 didn't exist when developed).

-Daniel

**Comment by theosp** [comment]
See commit: 4dc2fceead51c18a23172b8bfc70e2c61bed477d

**Comment by TimoRuetten** [comment]
@theosp Thanks a lot! I did not figured out which version was used - but your link helped. It works fine :)
