### ISSUE TITLE
Update simple-schema dependency to avoid errors in Meteor 1.3

### ISSUE THREAD

**Issue by martijnwalraven** [TAPevents/tap-i18n#147]
We've had to remove a workaround in Meteor 1.3, which leads to the issue previously reported in #104 reappearing: 

```
toEnd: wrong arguments-i18n-compiler` fr...  /

to: wrong arguments
```

This is due to `shelljs` (which is a dependency of the Cordova packages we use) modifying `String.prototype` to add `to` and `toEnd` functions, and this conflicting with the `stringjs`. The current version of `tap:i18n` depends on `simple-schema` 1.3.0, which has a dependency on `stringjs`.

I don't know enough about this project and the reasons for depending on an older version of `simple-schema`, but is there any way you could upgrade?

Since `simple-schema` [has now removed the `string.js` dependency](https://github.com/aldeed/meteor-simple-schema/pull/480), that would at least solve the issue until this has been fixed in `shelljs` and the Cordova packages that use it have updated their dependencies.

**Comment by theosp** [comment]
Which simple-schema version to try test with?

**Comment by martijnwalraven** [comment]
I would try the most recent version, but at least the one after the string.js dependency was removed.
