### ISSUE TITLE
Meteor 1.3 Cordova CORS problem with Beta 12

### ISSUE THREAD

**Issue by kations** [TAPevents/tap-i18n#152]
Hi everyone,

having a problem with CORS and Meteor 1.3 Beta 12 on iOS and Android with i18n.

The Error is the following:

iOS:
XMLHttpRequest cannot load https://app.soon.com/tap-i18n/de.json1. Origin http://localhost:12392 is not allowed by Access-Control-Allow-Origin.

Android:
XMLHttpRequest cannot load https://app.soon.com/tap-i18n/de.json1. The 'Access-Control-Allow-Origin' header has a value 'http://meteor.local' that is not equal to the supplied origin. Origin 'http://localhost:12392' is therefore not allowed access.

So both Apps can't download the json from Server. I also have set App.accessRule('*'); in mobile config but no luck.

Hope someone could help me with this problem. Btw. hosting is on Meteor Galaxy.

regards
thomas

**Comment by fignuts** [comment]
I have the same issue. After upgrading to Meteor 1.3 I can't get my apps to run on iOS or Android because of this.

**Comment by choemi** [comment]
I have the same problem with Meteor 1.3. When calling `TAPi18n.setLanguage("de")` I get an error `Couldn't load language 'de' JSON: errror` It does only apply for Cordova (iOS & Android), not for web.

**Comment by choemi** [comment]
solved problem by adding https://github.com/TAPevents/i18n-bundler and adding path to JSON language files in the config here: https://atmospherejs.com/tap/i18n#configuring-tap-i18n

**Comment by aqib1604** [comment]
Thanks @choemi working for me.

**Comment by derwaldgeist** [comment]
@choemi Is there a way to solve this if the language bundles are located in Meteor packages?

**Comment by choemi** [comment]
I don't know. I stopped working on this project, sorry.

2017-07-17 0:57 GMT+02:00 Tom Brückner <notifications@github.com>:

**Comment by derwaldgeist** [comment]
Ah, thanks anyway for the fast response.
