### ISSUE TITLE
Packages translations not merged on server startup

### ISSUE THREAD

**Issue by lubianm** [TAPevents/tap-i18n#161]
After upgrading to Meteor 1.3.1 we're experiencing an issue with packages translations on development environment. On our project we're managing translations on both top-level of sources ([root]/i18n/en.i18n.json) and on some other custom packages we've created. On those packages, translations are always kept in the same relative place ([root_of_package]/i18n/en.i18n.json) and on each package we've defined a root file **package-tap.i18n** with this content:
`{
    "namespace": "project"
}`.
The problem is that on each server startup we lose packages translations, because they are missing (looking on client's built package) on .js package file. No problem, instead, with "master" translations. The strange thing is that if we modify one of *.i18n.json package file (and we do not restart the server), the .js built file is correct and it contains the translations (until next server restart).
Is there anyone else experiencing the same problem ?

**Comment by benlavalley** [comment]
There were some fixes added to Meteor 1.3.2.1 that resolved some tap:i18n issues. Not sure if it is related, but felt it was worth sharing as 1.3.2 otherwise totally breaks tap:i18n.

https://github.com/meteor/meteor/issues/6806

**Comment by nixoz** [comment]
Hi guys...Looks like this one still an issue...
