### ISSUE TITLE
Meteor 1.3.2.2 - 'meteor test' with server TAPi18n.__() call fails with "TypeError: Object [object Object] has no method 'en'2

### ISSUE THREAD

**Issue by waitem** [TAPevents/tap-i18n#162]
I am working on a Meteor 1.3.2.2 project, and use `meteor test` for my unit testing.

I just added the tap:i18n package, but unfortunately in doing so, it causes `meteor test` to crash if I use the TAPi18n.__() method on the **server**. The stack trace is shown below.

To reproduce the problem, please see the following repository: [https://waitem@bitbucket.org/waitem/meteor-i18n-testing-issue.git](https://waitem@bitbucket.org/waitem/meteor-i18n-testing-issue.git)

In particular, the line that triggers the problem during testing is in `server/main.js`: 

`let appName = TAPi18n.__('app.name');`

`meteor run` works fine, and the translated app name is printed to the server console.

However, `meteor test` fails with the following stack trace: 

```
TypeError: Object [object Object] has no method 'en'
W20160418-13:36:34.935(10)? (STDERR)     at [object Object].__ (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:26:16)
W20160418-13:36:34.935(10)? (STDERR)     at myServerFunc (server/main.js:6:27)
W20160418-13:36:34.935(10)? (STDERR)     at server/main.js:14:5
W20160418-13:36:34.935(10)? (STDERR)     at /tmp/meteor-test-runkihh1b/.meteor/local/build/programs/server/boot.js:290:5
```

**Comment by waitem** [comment]
Unfortunately this is still an issue after upgrading to meteor 1.3.2.2

**Comment by thebarty** [comment]
just letting you know that I got the same issue and NO solution.

At least after 2 hours waisted in debugging and searching for a solution I finally found this topic and now I know that I am NOT the only one.

it seems like the json files are simply NOT loaded/recognized when being in unit-test-mode.

You can see that NO languages have been loaded by looking at the output:
````
    console.log('TAPi18n.getLanguages()')
    console.log(TAPi18n.getLanguages())
    console.log('TAPi18n')
    console.log(TAPi18n)
```

shows:
````
I20160522-16:43:01.439(2)? TAPi18n
I20160522-16:43:01.440(2)? { domain: null,
I20160522-16:43:01.440(2)?   _events: {},
I20160522-16:43:01.440(2)?   _maxListeners: 10,
I20160522-16:43:01.440(2)?   _fallback_language: 'en',
I20160522-16:43:01.440(2)?   _language_changed_tracker: { _dependentsById: {} },
I20160522-16:43:01.440(2)?   _loaded_languages: [ 'en' ],
I20160522-16:43:01.440(2)?   conf: null,
I20160522-16:43:01.440(2)?   packages: {},
I20160522-16:43:01.440(2)?   languages_names: {},
I20160522-16:43:01.440(2)?   translations: {},
I20160522-16:43:01.441(2)?   server_translators: {},
I20160522-16:43:01.441(2)?   __: [Function] }
I20160522-16:43:01.444(2)? TAPi18n.getLanguages()
I20160522-16:43:01.444(2)? null
````

**Comment by poltorak** [comment]
+1 same here, Meteor 1.3.2.4 and it stoping me from testing server methods

**Comment by abhiaiyer91** [comment]
My app won't even run due to this same issue. Is there an intended fix?

**Comment by tmeasday** [comment]
You need to make sure you import your translations file. In (non-full-app) test mode, your translations file won't automatically get imported (i.e. no eager loading).

You could add:

```
// import this
import '../i18n/en.i18n.json';

// before calling any translations
import { myServerFunc } from './main.js';
```

Or, probably better, you put your translation in `imports/`, and explicitly import your translations from `main.js`.

**Comment by poltorak** [comment]
@tmeasday how can I make 
`import '../i18n/en.i18n.json';`
work?

It throws me an error: ` Cannot find module`.

Of course I setup proper path to my translation file.

**Comment by tmeasday** [comment]
@poltorak that solution doesn't fix the problem in the linked reproduction app (if you add it to `server/main.js`)?

**Comment by poltorak** [comment]
@tmeasday Yes, this solution fix the problem in linked reproduction but my problem is quite different. I have package (with no traslation, I got only one global translation in i18n dir) and it brokes when I try to test package with command `meteor test-packages`. Without test (in normal mode) it works fine. Should I import some test translation file? Or maybe there is any other way to resolve that?

**Comment by tmeasday** [comment]
@poltorak, yeah if the translations are defined in the app and you run `test-packages`, there's no way the translations will come across.

In the Todos example we stub out `{{_` to help with a similar problem: https://github.com/meteor/todos/blob/master/imports/ui/components/client/lists-show.tests.js#L17-L23

Perhaps that would help? Probably it'd make sense for this package to include a way to "mock" a language for testing.

**Comment by poltorak** [comment]
@tmeasday Thank you very much. I already use this solution for testing on client but on server I use `try` `catch` for now to prevent crashing app. I thought maybe there's some other workaround :)
