### ISSUE TITLE
not working in Meteor 1.3.2.4 while tap-i18n defined in package

### ISSUE THREAD

**Issue by chongwang87** [TAPevents/tap-i18n#166]
i created a simple repro of the issue https://github.com/chongwang87/testTAP

the languages file `packages/lib/i18n/en.i18n.json` didn't work. 
if move  `packages/lib/i18n` to `i18n` (root), then it'll works.

reported in meteor as well https://github.com/meteor/meteor/issues/6941

**Comment by abhiaiyer91** [comment]
Same here man. i18n blows up on the server

**Comment by Andrew1431** [comment]
Any progress on this?

**Comment by YY030913** [comment]
Any progress on this?

**Comment by deeeed** [comment]
same issue
