### ISSUE TITLE
Default Language Is Arabic

### ISSUE THREAD

**Issue by TheRealNate** [TAPevents/tap-i18n#167]
Hey there,

I am using Tap-i18n but ever since I added arabic the default/fallback language is always arabic. I am assuming this is because it is in alphabetical order. How do I make the default/fallback language english?

**Comment by chongwang87** [comment]
you can always set your own default language on meteor startup

````
Meteor.startup(function() {
    TAPi18n.setLanguage('en');
});
````

**Comment by TheRealNate** [comment]
@chongwang87 
Object #<Object> has no method 'setLanguage'

There error prevents startup.
