### ISSUE TITLE
extraction of strings?

### ISSUE THREAD

**Issue by dcsan** [TAPevents/tap-i18n#18]
is there any tool to extract strings from a UI to make a base .json file?

**Comment by Elfoslav** [comment]
Try this script https://gist.github.com/Elfoslav/f7a0b8040706fd1f1fb8 It worked for me.

**Comment by xaiki** [comment]
please make this part of the documentation !

**Comment by ubald** [comment]
I have the same issue. I'm currently using https://github.com/i18next/i18next-parser, it will output every language in it's own directory (can't change unless I fork), but as long as the files are named the way tap-i18n wants them it works.

**Comment by dalerka** [comment]
+1 to have this feature as part of the package or better recommendation in docs. Couldn't find an easy way to extract strings automagically  :)
Thank you guys for your awesome work!

**Comment by Basgrani** [comment]
+1 Yes, I think it would be great if this feature is present in the package, but until then, I propose that the following combination of tasks for grunt, for my, working perfectly:

Extract to .po with: https://github.com/arendjr/grunt-xgettext

Convert .po to JSON with: https://github.com/rockykitamura/grunt-po2json

Sample configuration (in Gruntfile.js):

```
       // Build POT
        xgettext: {
            target: {
                files: {
                    handlebars: ["client/views/**/*.html"],
                    javascript: [
                        "client/**/*.js",
                        "lib/**/*.js",
                        "server/**/*.js"
                    ]
                },
                options: {
                    functionName: "tr",
                    potFile: "translations/messages.pot"
                }
            }
        },

        // Build JSON
        po2json: {
            target: {
                src: ["translations/*.po"],
                dest: "lib/i18n/",
                options: {
                    stringify: false,
                    stringOnly: true
                }
            }
        },
```

Keep in mind that we have here changed the name of the function for templates:

```("helper_name": "tr")```

and same for the .js files:

```
// Wrapper for TAPi18n
tr = function(key, options, lang_tag) {
    return TAPi18n.__(key, options, lang_tag);
};
```


I hope that it will help :)
