### ISSUE TITLE
Tool to easily get list of unused translation strings?

### ISSUE THREAD

**Issue by brylie** [TAPevents/tap-i18n#189]
We would like a list of translation strings/tokens that are no longer in use in our project, so we can clean them up. For example, there are a lot of tools surrounding the gettext approach, including the ability to [audit project source to locate unused (obsolete) strings](http://stackoverflow.com/a/27177726/1191545).

Is there any tooling available to quickly audit/manage project translation strings?

**Comment by TMeerhof** [comment]
We use <https://github.com/i18next/i18next-parser> in our project and it works like a charm for adding and removing strings

**Comment by brylie** [comment]
@TMeerhof thanks for the suggestion. Could you please provide an example of how you use the i18next-parser to extract your keys? I am not familiar with the options.
