### ISSUE TITLE
supporting multiple nested translation files

### ISSUE THREAD

**Issue by jakobdamjensen** [TAPevents/tap-i18n#19]
It would be neat if you could support multiple files with same "namespaces" like this:

```
{
  "module": {
      "submodule1": {
           "translation": "lalala"
      }
}

{
  "module": {
      "submodule2": {
           "translation": "lalala"
      }
}
```

Right now these should be in same file like so:

```
{
  "module": {
      "submodule1": {
           "translation": "lalala"
      },
      "submodule2": {
           "translation": "lalala"
      }
}
```

But being able to split them into several files would be nice =)

**Comment by gwendall** [comment]
Would be nice. For instance a good use case is having an "error" property for packages.
Example: 2 packages make calls to methods. Each would have their i18n json data:

```json
"errors": {
  "package1": "Package #1 error"
}
```

```json
"errors": {
  "package2": "Package #2 error"
}
```

**Comment by Genroa** [comment]
Any news about this? This is strongly needed to keep big translations readable.
