### ISSUE TITLE
Use HTML tags inside translated strings.

### ISSUE THREAD

**Issue by llvasconcellos** [TAPevents/tap-i18n#191]
How can I prevent HTML entities being translated when using TAPi18n?
`
Like <b> not being translated to &lt;b&gt;?
`

**Comment by lfilho** [comment]
I think this is Blaze domain, not tap-i18n. Try `{{{_ 'your-key'}}}` (3 braces instead of 2)

**Comment by llvasconcellos** [comment]
@lfilho It works!!! 
Thanks for your quick reply!

**Comment by lfilho** [comment]
Feel free to close this issue then.

Opa! Outro abraço, só que eu tô na Alemanha hehehe.

**Comment by llvasconcellos** [comment]
@lfilho How can I achieve the same with TAPi18n.__()?
