### ISSUE TITLE
Using Namespace "project" in package

### ISSUE THREAD

**Issue by deeeed** [TAPevents/tap-i18n#197]
Hi, 

I have been trying to follow the doc to add i18n files directly into my package, but my packages translation files never get loaded.

Let's say my package is called "custom:tool".
I created package-tap.i18n with the following content:
{ "namespace": "project" }
And added the translation files in /i18n/en.i18n.json in the package.

The content of en.i18n.json is never merged with my main project files.
How can I call TAPi18n.__("some.package.key") ?
How can I implicitely tell the TAPi18n object to reference the translation from the given package with the given namespace?

**Comment by Allerion** [comment]
+1

**Comment by luixal** [comment]
Having the same problem. Any solution for this?

**Comment by Cerealkillerway** [comment]
Same problem for me; any solution?
