### ISSUE TITLE
Update to node-simple-schema

### ISSUE THREAD

**Issue by guidouil** [TAPevents/tap-i18n#198]
I was wondering if it was possible to update to [node-simple-schema](https://github.com/aldeed/node-simple-schema)? It's the new version of simple-schema.
I tried to do it for my project but hit a wall since it is required for TAPi18n.
Can you help me ?
[This the recipe I followed to try to update my project.](https://github.com/aldeed/meteor-collection2#important-note-the-version-in-this-repo-is-deprecated)

**Comment by kyv** [comment]
+1

**Comment by danyhiol** [comment]
+1
