### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by humbertocruz** [TAPevents/tap-i18n#199]
Hello,

I'm building a app where the default language is Portuguese Brazilian. My language files inside /i18n folder is based on the original portuguese words, not english. So, I need to build the portuguese files because if not, the translation will fallback for english. There is a way to change de fallback language for portuguese too, besides de default language ? Thanks

**Comment by krishaamer** [comment]
I need the same thing. Did you manage to find a solution @humbertocruz ?

**Comment by humbertocruz** [comment]
Hello Kris, no, not yet. The first version of the project will be only in Portuguese for now :)
