### ISSUE TITLE
tap18n not working with ecmascript

### ISSUE THREAD

**Issue by Cerealkillerway** [TAPevents/tap-i18n#200]
I use tap:i18n in 4 packages of my application; it was working fine until I had to add ecmascript as a dependency in all the 4 package.js files (otherwise the app will not build properly);

anyway after doing this i18n is not working anymore for all strings that are stored in packages' i18n folders...
I found a similar issue closed with a patch solution (to move all i18n strings in the i18n folder of the main app instead of keeping them inside the packages);
since this solution it's hard to mantain I'm opening this issue to find out if there is any progress about this big problem

**Comment by luixal** [comment]
I'll be glad to find some explanation about how to make a package using i18n and including its lang files. Including ```"namespace": "project"``` in `package-tag.i18n` doesn't seem to work for me...

**Comment by derwaldgeist** [comment]
This is a nightmare.
