### ISSUE TITLE
Problems using tag:i18n in a package

### ISSUE THREAD

**Issue by luixal** [TAPevents/tap-i18n#206]
My approach is having a package for lang support used by my main project and other packages. Something like this:

* **myapp-i18n**: here is were I want to keep my translations and an `I18N` helper that allows me to set lenguage, get user language, get translations, etc...
* **myapp-collections**: here is were I want to keep my collections (using collection2 and simpleSchema). As I use `tap:i18n` for translating collection labels, `myapp-i18n` would be a dependency of this package.
* **myapp**: main project. Here I will use collections from `myapp-collections` and translations and helper from `myapp-i18n` so both packages would be dependecies to this one.

While setting this up, I'm having some problems:

1. I have tried to use `I18N.__` and `__` functions inside my package, getting a `function is not defined` in both cases.
2. Once I've added `tap:i18n` to all projects and generated an `i18n` directory and `en.i18n.json` file inside in all package, things work, but no translations from `myapp-i18n` are imported in other projects (I've set the `"namespace"="project"` property with no luck).

Any ideas of what could I be doing wrong?

------
Now, the code part.
My `package.js` file from `myapp-i18n` package:

```javascript
Package.describe({
  name: 'myapp:myapp-i18n',
  version: '0.0.1',
  // Brief, one-line summary of the package.
  summary: 'MyApp i18n',
  // URL to the Git repository containing the source code for this package.
  git: '',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.4.4.1');

  api.use(['tap:i18n@1.8.1'], ['client', 'server']);
  api.addFiles("package-tap.i18n", ["client", "server"]);

  api.use(
    [
      'ecmascript',
      'less@2.7.9',
      'accounts-password@1.3.3',
    ]
  );

// some other dependencies and files are added right here...

  api.addFiles(
    [
      './i18n/en.i18n.json',
      './i18n/es.i18n.json',
      './i18n/ca-ES.i18n.json',
      './i18n/i18n.js',
    ],
    ['client', 'server']
  );
  // export public values:
  api.export(
    [
      'I18N',
      'Collection 1',
      'Colleciton 2'
    ],
    ['client', 'server']
  );
  api.mainModule('myapp-i18n.js');
});
```

the `package-tap:i18n` file:

```json
{
  "translation_function_name": "__",
  "helper_name": "_",
  "languages_files_dir": "i18n",
  "namespace": "project"
}
```

Any ideas?

**Comment by vpalos** [comment]
This is definitely a problem. I can confirm that no translations defined in a package are loaded (unified) with the project ones. I've also tested using a vanilla project /w empty package.

I suspect a recent version of Meteor might cause this breakage. @luixal what version are you using?

**Comment by vpalos** [comment]
The culprit is (at least at the surface) the "ecmascript" package. Just don't load it in the package and the translations should load normally.

**Comment by luixal** [comment]
Yes, I'm using Meteor 1.4.4.2 for testing this aaand... removing `ecmascript` from package works!

Funny fact: I did try this before (I read it somewhere else) but I guess that, as I tried many combinations, maybe I missed something.

Not having `emacscript` in my package is fine, as I'm using this package only to keep lang files, but can be a problem in other approaches.

Thanks @vpalos , I had left this for impossible!

**Comment by vpalos** [comment]
@luixal This is only a workaround. The `ecmascript` package is quite important and TAP must eventually be fully compatible with it. So maybe it's best to keep this ticket open.

**Comment by KCErb** [comment]
+1 here, having the same problem but I can't just turn off the ecmascript package.

**Comment by luixal** [comment]
@vpalos totally true. In my case, that package is part of a full app and it only contains lang files and exports the TAPi18n object for using it within the app. That's why the solution of removing the `ecmascript` package worked for me :)
