### ISSUE TITLE
No language labels showing up after upgrade to Meteor 1.3

### ISSUE THREAD

**Issue by derwaldgeist** [TAPevents/tap-i18n#208]
I finally got my app migrated from Meteor 1.2 to 1.3. But unfortunately, none of the i18n messages show up correctly. They only show the code strings. 

The app uses tap:i18n@1.8.2 and tap:i18n-ui@0.8.0. Is there any known incompatibility / upgrade path when moving from 1.2 to 1.3?

Note: My language files are mostly located in private Meteor packages.

I also found out that the "resStore" in the TAPi18next object is empty. So no file seems to be loaded.

**Comment by derwaldgeist** [comment]
The problem seems to be related to the `ecmascript` package. If this is included in the package, `tap:i18n`breaks. Otherwise, it works.

**Comment by INRIX-Yogesh-Randhawa** [comment]
Is this fixed? I am using Meteor 1.5 and I have translation files in a package but they don't seem to load/work at all. I just see code strings. The translations in the project folder work fine.

**Comment by derwaldgeist** [comment]
Have you tried to remove the ecmascript package? I could only get things working after I moved all i18n files to a separate package without ecmascript.

**Comment by INRIX-Yogesh-Randhawa** [comment]
No because I want to use ES6. So I had to move the translations out of this package and into the project. For now I am injecting translations into the package when I use that component from the package.

**Comment by derwaldgeist** [comment]
I solved it in a different way: I created an additional package for the i18n and removed ecmascript from that one. Worked.

**Comment by INRIX-Yogesh-Randhawa** [comment]
thanks... I will try that next time. But I hope TAP fixes this bug.

**Comment by derwaldgeist** [comment]
Yep, this is weird.
