### ISSUE TITLE
Workflow for adding translations - contributions

### ISSUE THREAD

**Issue by tosinek** [TAPevents/tap-i18n#217]
Hi, what would you recommend as a workflow to allow other people to contribute to translations?

One of my ideas is to create a view for users that would load the all translation files and merge them in a single view, showing e.g. what's not translated in each language. Once they fill in the gaps, that would be stored in the database. I would then generate a new json file and add it to the project (+git). This approach seems to be clunky as there is a delay in filling in the translations and actually seeing the updates on the page (unless I hack into the package somehow and merge the recent DB changes with the JSON files).

So the obviously better solution would be to store all the translations in the DB, similarly to the file structure. But that would be a big change in the package itself?

Do you have any recommendation on what's the best approach here? Should I be even using this package (I utilize all parts of it at the moment, core, ui and db)?

**Comment by theosp** [comment]
For db based i18n, check https://github.com/TAPevents/tap-i18n-db

**Comment by tosinek** [comment]
> For db based i18n, check https://github.com/TAPevents/tap-i18n-db

I have been already using it. It may be a solution maybe if I hack the -core helpers. Another problem with -db that others have reported is that it doesn't load all the translations at once, but only the single selected translation. Maybe I could hook into the collection twice in such case (once with the TAP.collection and then with regular Mongo.collection for translation management?).
