### ISSUE TITLE
Having issue during update to latest Meteor version

### ISSUE THREAD

**Issue by dnish** [TAPevents/tap-i18n#222]
Hey,
we are using tapi18n since a long time on our Blaze projects. If I try to update Meteor to the latest version, everything works fine, but after starting the application, I get the following error:

```
/Users/x/.meteor/packages/tap_i18n/.1.8.2.vx3ceq++os+web.browser+web.cordova/plugin.tap-i18n-compiler.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'undefined'
- 'boolean'
    at /tools/isobuild/bundler.js:1380:16

```

Any idea how I can fix it?

**Comment by Sagar-Shah33** [comment]
I am also facing the same issue could you have any idea how to fix it?

**Comment by evolross** [comment]
This package is long abandoned. Use one of the many forks that have been updated to work with the latest Meteor.
