### ISSUE TITLE
Compatibility Meteor 3.0

### ISSUE THREAD

**Issue by Marcel-Tronco** [TAPevents/tap-i18n#229]
Hi there,
will there be Meteor 3.0 compatibility when meteor 3.0 will be published ? 
Great to see that there's happening something in the development in meteor and your library too. As you'll know meteor will finally update to a current node.js version in the nearer future. I'm maintaining a meteor app and wanted to evaluate how much work it will be to migrate. Step one is to estimate how many packages will need to be replaced.

Atm tap-i18n has some dependency conflicts with the current alpha (3.0-alpha.19) . I'll copy the line from the meteor shell:
```
webapp@1.1.4 <- cfs:http-methods 0.0.32 <- tap:i18n 1.10.2
```
Best Marcel

**Comment by Marcel-Tronco** [comment]
Just saw, that there's a pull request in regard to exactly this...

**Comment by theosp** [comment]
Yes, we are working on it, Brian is on the team. It still needs some testings and we'll ship it out.

**Comment by theosp** [comment]
Marcel if it isn't confidential, I'd love to know what you use tap:i18n for.

**Comment by theosp** [comment]
v1.11.0 is ready `meteor update tap:i18n` to get it.
