### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by zimt28** [TAPevents/tap-i18n#24]
I'm using [yoolab/iron-router-i18n](https://github.com/yoolab/iron-router-i18n) to set the language depending on the url. The package uses a hook to set the language, but not for the default language. The configuration looks like this:

``` javscript
Router.configure({
  i18n: {
    defaultLanguage: 'de',
    languages: ['de', 'en'],
    setLanguage: function (lang) {
      if (Meteor.isClient) {
        TAPi18n.setLanguage(lang);
      }
    }
  }
});
```

I tried to use a startup script to set a default language for tap-i18n:

``` javascript
// both/startup.js
if (Meteor.isClient) {
  Meteor.startup(function () {
    TAPi18n.setLanguage('de');
  });
}
```

The problem is, that this startup script seems to override the hook when the app runs on a production server. I think this might be because of some async behavior. Is there a better way to set the default language than just using the `setLanguage` function? 

If I get this package right, I'm looking for a way to set a custom [fallback_language](https://github.com/TAPevents/tap-i18n/blob/master/lib/globals.js#L5), that is not async.

**Comment by Elfoslav** [comment]
+1 I have existing app with keys in German language, so I need to set default language to "de".

**Comment by zimt28** [comment]
What exactly is your problem? Maybe I can help :)

**Comment by Elfoslav** [comment]
I have en.i18n.json file and english translations in it. English translations are shown by default. When I want to change language to "de", nothing happens if I don't have de.i18n.json and all key:values in it. I don't want to have de.18n.json file with duplicated strings.

**Comment by zimt28** [comment]
What do you mean with "duplicated strings"?

**Comment by Elfoslav** [comment]
if de.18n.json contains:

{ 
    "senden": "senden",
    "bestätigen": "bestätigen"
}

then I can see translation in app for TAPi18n.__('senden'), TAPi18n.__('bestätigen'). But without these duplicated strings in de.18n.json I see english translations from en.18n.json even if language is "de", because "en" is default language.

**Comment by zimt28** [comment]
Ok, got it. This is totally correct! In your case it may feel wrong as you're translating single words and use the same word to describe them (the key), so they're duplicate.

**Comment by theosp** [comment]
Hi,

Small terminology clarification:

en is used as the Fallback Language, it is streamed to the client as part
of the bundle and not using ajax (to avoid flickering, and always have it
available). If we can't find a string in a language that isn't english we
will show the english translation.

If a string doesn't available in the fallback language we show the key
itself.

There is no definition in tap:i18n for Default Language.

-Daniel

**Comment by theosp** [comment]
README needs to be updated according to my last message, sorry :|

**Comment by theosp** [comment]
https://github.com/TAPevents/tap-i18n/commit/02af57a5ac644112ab7c5996355f31a06c3cb667

**Comment by Elfoslav** [comment]
I can see fallback language is set in globals.js https://github.com/TAPevents/tap-i18n/blob/master/lib/globals.js Can we configure tap-i18n to use different fallback language? I don't see it in README. This is actually what I want - ability to configure fallback language.

**Comment by almogdesign** [comment]
+1

**Comment by dalgard** [comment]
+1

**Comment by hitchcott** [comment]
With hindsight this would be extremely useful for projects that do not support english, but use 3rd part packages that support tap:i18n - like https://github.com/hitchcott/meteor-paginator :)

**Comment by theosp** [comment]
@Elfoslav , answered here: https://github.com/TAPevents/tap-i18n/issues/24#issuecomment-59798528

**Comment by parhelium** [comment]
+1

**Comment by bompi88** [comment]
+1

**Comment by louis49** [comment]
+1

**Comment by R0binT** [comment]
+1

**Comment by b1gbrother** [comment]
+1

**Comment by SergeThiriet** [comment]
+1

**Comment by maevaD** [comment]
+1

**Comment by YannDanthu** [comment]
+1

Useful missing feature :)

**Comment by juliomac** [comment]
+1. Very important !

**Comment by krishaamer** [comment]
Also need to set a non-english default language. Has this been implemented?

**Comment by FrancisBou** [comment]
+999

**Comment by m3t4l1c** [comment]
+1

**Comment by krishaamer** [comment]
+1

**Comment by jlmbaka** [comment]
+1

**Comment by namenotrequired** [comment]
I made a fork with Brazilian Portuguese (`pt-BR`) as fallback language, you can install it here: https://atmospherejs.com/bartoftutormundi/tap-i18n

If anyone wants to follow in my footsteps to publish their own version with another fallback language, see the changes I made in the latest commits: https://github.com/namenotrequired/tap-i18n/commits/master
