### ISSUE TITLE
pass object to helper

### ISSUE THREAD

**Issue by sclausen** [TAPevents/tap-i18n#29]
It would be great, if you could pass an object to the helper instead of hardcoding key-value pairs or plain strings. Like `{{_ error_message object}}`.

``` javascript
var metadata = {
  filename: "testfile.mp4"
};

Movies.insert(movie, function (err) {
  // err.message = "file_upload_error";
  // err.metadata = metadata
  ShowMessage.error(err.message, err.metadata);
});

// i18n/en.i18n.json
{
  "file_upload_error": "There was an error uploading the file _filename__!"
}
```

ShowMessage would be doing stuff which would render message templates which contain the translation helper somewhere.

[EDIT]: I would make a pull request, but unfortunately this project is in coffeescript :-/

**Comment by sclausen** [comment]
@grigio: unfortunately your version isn't sufficient for my usecase, the thing is that I have arbitrary keys  and therefor can't declare the variables in the helper. Like in my example, I have to pass an object with the variables along to the translation key which is a variable and not a string.

**Comment by theosp** [comment]
Hi @sclausen ,

I am designing support for your use case [for v1.4](https://trello.com/b/w80JNkwf/tap-i18n-roadmap), you (and all who interested) are welcome to join to its design process:

https://hackpad.com/Allow-passing-an-object-with-named-variables-to-the-translation-helpers-UN507cVbjMU

Daniel,
[Meteor Developer](http://www.meteorspark.com)

**Comment by jykae** [comment]
@theosp @sclausen Still under proposal? not possible with current TAPi18n ?

**Comment by sclausen** [comment]
@jykae sorry, this issue is too old, I'm not using meteor currently anymore. If anyone still has this issue with current TAPi18n one should open another on ;)
Thanks for your work!
