### ISSUE TITLE
Can't get right language name

### ISSUE THREAD

**Issue by fanshuai** [TAPevents/tap-i18n#36]
[lib/globals.js : 6] (/TAPevents/tap-i18n/blob/9ca8d757abc58d8d1ba03bd5357f99f6fea131a2/lib/globals.js#L6)
> langauges_tags_regex: "([a-z]{2})(-[A-Z]{2})?",

so i config a i18n file named "zh-TW.i18n.json"
and console 
>TAPi18n.getLanguages() 

but it return 
> { zh-TW: {en: "zh-TW", name: "zh-TW" }}

not 
[tap-i18n/lib/plugin/etc/language_names.js : 24] (/TAPevents/tap-i18n/blob/9ca8d757abc58d8d1ba03bd5357f99f6fea131a2/lib/plugin/etc/language_names.js#L24)
> "zh-tw": ["Chinese (Taiwan)","中文"], 

so
[lib/plugin/compilers/i18n.json.coffee : 48] (/TAPevents/tap-i18n/blob/3d68193d764471248472961a7e9284fc7fba53e8/lib/plugin/compilers/i18n.json.coffee#L48)
> if language_names[language]?

is need lower the language tag string ?

**Comment by theosp** [comment]
Fixed, thanks
