### ISSUE TITLE
`getLanguages()` returning disabled languages

### ISSUE THREAD

**Issue by hitchcott** [TAPevents/tap-i18n#38]
I have a project with two sets of language files in `/i18n`

* `en.i18n.json`
* `zh.i18n.json`

I have my `/project-tap.i18n` as such (only enabling `en`): 

```
{
  "supported_languages" : ["en"]
}
```

`TAPi18n.getLanguages()` is expected return only `{en: Object}`, but returns `{en: Object, zh: Object}`

zh is definitely disabled:

```
> TAPi18n.setLanguage('zh').fail(function(err){console.log(err);})
> ["Language zh is not supported"]
```

**Comment by theosp** [comment]
Fixed, along with other issues in v1.3.1 check ChangeLog
