### ISSUE TITLE
getting rid of Ajax calls?

### ISSUE THREAD

**Issue by splendido** [TAPevents/tap-i18n#39]
what would you think about using a dedicated `i18n` collection to store all the json docs for available languages and than play with publish/subscribe to actually get the data for the selected language on the client?

I feel this would be a better meteoric way to load i18n data on the client...
But this is almost random thoughts, I haven't had a chance do dig your code ;-)

**Comment by theosp** [comment]
Hi @splendido ,

Since translations are changed very rarely, using the database to store them and the ddp to deploy them is a waste of resources.

Actually, one of the main reasons to go to develop tap:i18n was to have much more efficient way to deploy translations.
With tap:i18n translations files can be stored easily on a cdn, and you need to load only one translation file per language (all the files belonging to a language are unified in the build process), all these reasons makes tap:i18n the most efficient i18n package for Meteor.

Saying all that, if you do want to implement collection+pub/sub solution on top of tap:i18n you can do it easily with the fresh loadTranslations() api. Though we discourage that in the README ;)

Thanks,
-Daniel
[Meteor Developer](http://www.meteorspark.com/)

**Comment by theosp** [comment]
Another two points:
* a collection based solution is not good when you want to i18n a package (a package shouldn't use resources that aren't absolutely necessary).
* Interface translations are integral part of the code and are edited in the course of development, therefore it is best to have them as a file that can be easily tracked using a version control system according to get the right version of translation for each version of the code.

**Comment by splendido** [comment]
...what do you mean with a

> using the database to store them and the ddp to deploy them is a waste of resources

are you referring to the db space costing more than regular disk space?

I'm quite sure dealing with a client subscriptions might have its advantages too:
- you can easily subscribe to a different language (or to more than one language at the same time...)
- you can know for free when the subscription is ready
- any change to the translation files will *instantly* reach the client without need to reload the page (even if this might be a rare usecase as you're pointing out...)
- you wouldn't need a CDN and you wouldn't need to set CORS on your CDN
- loading through DDP might be faster than through ajax calls
- ...

Still keeping translations on files, you could have them built at server startup and updated on the db accordingly (basically wiping out the old version and substitute it with the new one...).

But, again, this is some consideration based on my Meteor experience, if you already evaluated the option and went for a different solution you'd had your reasons for it ;-)

Tnx for the discussion!

**Comment by splendido** [comment]
...one last thought:
you could even think about using `*.i18n` files and roll your own build tool to pick up any changes to the translation files and reflect them on the db during development ;-)

**Comment by theosp** [comment]
@splendido ,

First, splendido:i18n-collection package that implements collection+pub/sub based solution on top of tap:i18n is welcome. Once it'll be stable I will even refer to it from the README.

* I can think of a jsonp feature that won't require CORS for CDNs.
* By resources I mainly mean CPU and memory usage for the DDP and DB usage (why go through Meteor if you really don't need to).

-Daniel

**Comment by splendido** [comment]
I'm sorry I have only little time...
...I'd be happy to play with this but unfortunately I can't :(

If you speak about CPU and memory usage I might agree with you ;-)

Btw I didn't mean, anyhow, to say your solution is not good.
Just wanted to know your thoughts about using collections and pub/sub...

Tnx again for the chat!

**Comment by theosp** [comment]
Sure, I didn't think that raising different opinion means you think tap:i18n is not good. And anyway in the open source world, the idea of fork brings peace to any argument ;) .

**Comment by lowi** [comment]
@theosp ,

I am working on a meteor project and we are using tap-i18n for the translation.

We have developers and remote translators working concurrently on the translation files, and I am thinking of creating a package to offer the following features:
 - add/overwrite translation for keys through a grid view and store them in a collection
 - use the new translation by loading them through loadTranslations
 - possibility to download the overriden translations to a .json file to integrate them in the application for deployment

Any advice about when to call .loadTranslations? Is it something to call on the server & client?

The alternative is to give the translators access to github and let them modify directly the .json file.
