### ISSUE TITLE
Allow users to define preloaded languages

### ISSUE THREAD

**Issue by d4nyll** [TAPevents/tap-i18n#40]
At the moment, only the default language (`en`) is preloaded. So if my site's default language isn't `en`, then the JSON file doesn't get pre-loaded and I may get a momentary flash where the placeholder text can be seen.

Thus, I propose an enhancement where we allow the user to define which languages should be preloaded.

**Comment by almogdesign** [comment]
+1

**Comment by almogdesign** [comment]
This would be great and would also solve the issue with setLanguage not working in offline mode https://github.com/TAPevents/tap-i18n/issues/48

**Comment by nowakstefan** [comment]
+1

**Comment by rbabayoff** [comment]
+1, this is especially crucial in cordova apps, that require offline support for users that don't use the default language.

**Comment by rbabayoff** [comment]
Any update on this?

**Comment by rbabayoff** [comment]
Can I create a PR?

**Comment by theosp** [comment]
Hi,

v1.6-rc1 can be found here https://github.com/TAPevents/tap-i18n/tree/v1.6-rc1

Please read the docs related to the new project-tap.i18n option `preloaded_langs`: https://github.com/TAPevents/tap-i18n/tree/v1.6-rc1#configuring-tap-i18n

In about a week v1.6 will be published, by then, please report issues if you encounter any.

Thanks,
-Daniel
