### ISSUE TITLE
aldeed:simple-schema - Constraints

### ISSUE THREAD

**Issue by stachrom** [TAPevents/tap-i18n#42]
Hi theosp

I like to update from tap:i18n  1.2.1 to tap:i18n 1.3.1
tap-i18n 1.3.1 is bound to  aldeed:simple-schema --> 0.7.0.
My project is currently on the latest version aldeed:simple-schema --> 1.3.0.

This leads to an update error: 

 => Errors while adding packages:             
                                              
While selecting package versions:
error: conflict: constraints on aldeed:simple-schema cannot all be satisfied.
Constraints come from:
aldeed:autoform@4.2.2
aldeed:collection2@2.3.1
tap:i18n@1.3.1

Regards roman

**Comment by theosp** [comment]
I can take care of it only Sunday.

A pull request is welcomed.

-Daniel

**Comment by theosp** [comment]
Published v1.3.2 that uses simple-schema 1.3.0

**Comment by theosp** [comment]
Starring tap:i18n will be appreciated :)

**Comment by stachrom** [comment]
done :-) thanks.

**Comment by jadsonlourenco** [comment]
And how to use it in a schema? I tried what the guy said here: https://github.com/aldeed/meteor-autoform/issues/483 (last answer) but not work.

Thanks!

**Comment by jadsonlourenco** [comment]
Ok I get this package working with https://github.com/aldeed/meteor-autoform: 
```
Schema.signIn = new SimpleSchema({
    email: {
        type: String,
        regEx: SimpleSchema.RegEx.Email,
        label: function() {
            return TAPi18n.__('signin_form_input_email');
        },
    },
    password: {
        type: String,
        label: function() {
            return TAPi18n.__('signin_form_input_password');
        },
    }
});
```

Thanks again!

**Comment by lfilho** [comment]
@jadsonlourenco ooh, nice catch! But it didn't work for me. What versions are you using?

**Comment by lfilho** [comment]
Going further with @jadsonlourenco solution, I did the following in order to keep it more readable:

```
function __(key) {
    return TAPi18n.__.bind(TAPi18n, key);
}
```

So you can use it just like:
```
password: {
   type: String,
    label: __('signin_form_input_password')
}
```

Of course one can name it whatever they like
