### ISSUE TITLE
Requesting non-preloaded language from client side breaks TAPi18n

### ISSUE THREAD

**Issue by hamoid** [TAPevents/tap-i18n#54]
According to http://i18next.com/pages/doc_features.html, if you request a translation in a language which has not been preloaded, it should be fetched synchronously. But for some reason this fails and TAPi18n lo longer works after that.

**Comment by theosp** [comment]
Provide more details on what you are doing, preferably with actual project example.

Do you use the feature documented the section titled [access value in different language](http://i18next.com/pages/doc_features.html) in i18next docs?

Thanks,
-Daniel

**Comment by hamoid** [comment]
Yes, that's what I'm trying to do, what's shown in the i18next docs.
If I try to ```TAPi18n.__('key', { lng: 'es' })``` but 'es' is not loaded, TAPi18n stops working.

I discovered I had to preload the languages to make it work. Here what I ended up doing:
https://stackoverflow.com/questions/29153392/tapi18n-how-to-show-text-in-several-languages-side-by-side

**Comment by theosp** [comment]
Please test this pull request: https://github.com/TAPevents/tap-i18n/pull/55

**Comment by hamoid** [comment]
Wow thanks a lot for working on it! It seems to work fine from inside a helper. I can see it works because it takes a fraction of a second for the translation to appear. With this I can already make the code much cleaner :)

For some reason the current language is always shown if I try to use the new feature from a template. {{_ key lang="es"}} shows the current language, not "es", and it's reactive. If I change the current language from the menu the text changes, instead of showing "es".

**Comment by hamoid** [comment]
It could also be that I've done something wrong. I pulled the branch into a packages folder inside my project, and I noticed it was using the new version because TAPi18n got new methods (I checked in the browser console). Is there anything else I should do to replace the original version with the new one?

**Comment by theosp** [comment]
You are welcome! The demand for this feature is very high and I felt like it's really missing in the API.

If you appreciate my work, know that you and your fellow programmers can use my services throw my [Meteor Development consultancy](http://www.meteorspark.com/). And please star tap:i18n :)

Regarding your issue, you should use `lng` and not `lang`, that's quite confusing, so I am going to make `lang` an alias option to `lng`.

-Daniel

**Comment by theosp** [comment]
[Done here](https://github.com/TAPevents/tap-i18n/commit/d3a4574f435fc035baeebe34aeca88547d4cc186) please test again and let me know if it works well.

Thanks,
-Daniel

**Comment by hamoid** [comment]
Works great. Beautiful :) I'll mention your services to my employer :+1:

**Comment by hamoid** [comment]
I'm having a strange issue with the translations, and I wonder if it's related to the changes in the new branch. Sometimes when I click a link the page switches to Spanish. 

When that happens, in the console I type TAPi18n.getLanguage() and it prints "en". But TAPi18n.__('homepage') prints "Página de inicio". If I run TAPi18n.__('homepage', { lng: 'xx'}) where xx is 'de', 'en', 'es', it always responds with the Spanish version.

If I reload the page or choose English in the menu (which is already selected), it's back to normal. The fallback language is 'en'. loaded_languages is ['en', 'es', 'de'].

What could I do to debug this?

**Comment by hamoid** [comment]
I suspect it's related to TAPi18n, because I'm also using T9n (which is required by useraccounts:bootstrap) and the log out button (translated by T9n) is the only thing correctly shown in English.

**Comment by hamoid** [comment]
I'm having a rare random behaviour I can't reproduce. Sometimes the page is displayed in one language, but TAPi18n.getLanguage() in the console prints a different language. Also this different language is shown as the active one in the language menu. When this happens I can fix it by reloading the page, or by selecting the language that should be visible already from the language menu. It's hard to debug because it's rare. When I look for it, I click on 100 internal links and it does not manifest itself. When I stop looking it may happen twice in one minute.

How is it possible that TAPi18n thinks a certain language is the current one, but displays the texts in a different one? Is it maybe in an odd state, in which two internal variables are out of sync?

I was setting the initial language on rendered(), I just placed it on Meteor.startup() to see if it makes a difference.

**Comment by hitchcott** [comment]
Hi @hamoid -- are you using just `tap:i18n` or `tap:i18n-db` too?

**Comment by hamoid** [comment]
Hi @hitchcott -- only tap:i18n, specifc-language-translation-client branch (I need to show multiple languages on the client side simultaneously). I also use softwarerero:accounts-t9n@1.0.9 (required by a package, no idea if that makes a difference)

**Comment by hamoid** [comment]
I think this shows that there must be something strange going on. In the console:

```
TAPi18n.getLanguage()
  "es"
TAPi18n.__('homepage')
  "Startseite"
TAPi18n.setLanguage('es')
  Object {state: function, always: function, then: function, promise: function, pipe: function…}
TAPi18n.__('homepage')
  "Página de inicio"
TAPi18n.getLanguage()
  "es"
```

It's returning first German and then Spanish, even if in both cases it thinks the current language is Spanish.
