### ISSUE TITLE
How to call translation helpers on js?

### ISSUE THREAD

**Issue by yuomtheara** [TAPevents/tap-i18n#57]
I use ` simple-schema` with `auto-form` to generate form like this:
```
Branch = new SimpleSchema({
    khName: {
        type: String,
        label: "Kh Name", // {{_ "khName"}
        //unique: true,
        max: 200
    },
    khShortName: {
        type: String,
        label: "Kh Short Name",
        //unique: true,
        max: 200
    },
........................
```
So i want to call translation on js of simple-schema.

**Comment by theosp** [comment]
Hi,

Telescope project had the same issue take a look on what they did:
https://github.com/TelescopeJS/Telescope/search?utf8=%E2%9C%93&q=label

-Daniel
[Meteor Developer](http://www.meteorspark.com), MeteorSpark

**Comment by yuomtheara** [comment]
Thanks for your reply, but I don't understand.

**Comment by theosp** [comment]
Basically, whenever they want to print the label in the UI they pass it as a parameter to the `{{_ }}` helper.

See for example: https://github.com/TelescopeJS/Telescope/blob/bdc3e4eba4ae521b8490fb871a32654c7555bb63/client/views/nav/menu_item.html#L4

In their lang files they use the labels they used in the schema definitions as the key for translation.

See for example the `daily` label and its translations :
https://github.com/TelescopeJS/Telescope/blob/bdc3e4eba4ae521b8490fb871a32654c7555bb63/packages/telescope-daily/lib/daily.js#L5
https://github.com/TelescopeJS/Telescope/search?utf8=%E2%9C%93&q=daily

Hope that helps!
-Daniel

**Comment by yuomtheara** [comment]
Excuse me, have any js function to do this like `i18n.get('file.obj.key')` of `ostrio:i18n` ?
because I try see your link, but don't understand.

**Comment by Billybobbonnet** [comment]
I managed to do it with the following call. Note the double underscore.

`TAPi18n.__('my_string_to_translate');

or optionally

`TAPi18n.__('my_string_to_translate', my.argument);

**Comment by yuomtheara** [comment]
Thanks
