### ISSUE TITLE
TAPi18n._afterUILanguageChange() on page load not working

### ISSUE THREAD

**Issue by micabe** [TAPevents/tap-i18n#60]
Hi Daniel,
I have just started using Meteor.
I am using both packages  tap:i18n and tap:i18n-ui which are great. I have imported the select list to swap between languages with {{> i18n_dropdown }}. 
However when the DOM gets updated, TAPi18n._afterUILanguageChange() does not get triggered on first page load.. only after
Do you know why, how can it get fixed?

Your help is much appreciated.

Mickael

**Comment by micabe** [comment]
var storedLanguage = amplify.store('tap-i18n-language');

**Comment by hitchcott** [comment]
Yeah, `_afterUILanguageChange` is only for after user-triggered changes in the UI.

Take a look at the pending issue https://github.com/TAPevents/tap-i18n/issues/58 for a universal hook.
