### ISSUE TITLE
Issue with meteor-tabular

### ISSUE THREAD

**Issue by justindra** [TAPevents/tap-i18n#63]
Hi,

So I'm having a few problems when using the JS call to set the titles of the columns in [aldeed:meteor-tabular](https://github.com/aldeed/meteor-tabular).

I'm calling it this way,
````
TAPi18n.__('email')
````

And this is the error that I'm receiving.
````
TypeError: Object #<Object> has no method 'en'
    at Object.__ (packages/tap:i18n/lib/tap_i18n/tap_i18n-server.coffee:25:16)
````

Cheers!

**Comment by theosp** [comment]
Fixed in v1.5.1
