### ISSUE TITLE
Sever-side testing issue with SimpleSchema in Velocity 

### ISSUE THREAD

**Issue by laurentpayot** [TAPevents/tap-i18n#65]
Hi. I'm using the more or less "standard" meteor schema validation  package <b>aldeed:simple-schema</b> with the no less "standard" testing package <b>Velocity</b> (mocha syntax).
I'm using tap-i18n in the fields labels like so (CooffeScript):
<pre>
Authors.attachSchema(new SimpleSchema(
    'firstName':
        type: String
        max: 100
        label: -> TAPi18n.__('author_firstName_label')
    'lastName':
        type: String
        max: 100
        label: -> TAPi18n.__('author_lastName_label')
))
</pre>

Everything is working fine, in both English and French, except for server-side testing. Here's the mocha tests log:
<i>
[velocity-mirror] Mirror is initializing...
SETUP GLOBALS
Warning: language en is not supported in this project, fallback language (en)

/home/laurent/.meteor/packages/meteor-tool/.1.1.3.1y1ep5f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Object #<Object> has no method 'en'
    at Object.__ (packages/tap:i18n/lib/tap_i18n/tap_i18n-server.coffee:28:16)
    at __ (both/collections.coffee:14:11)
    at Object.Authors.attachSchema.SimpleSchema.firstName.label (both/collections.coffee:76:13)
    at packages/aldeed:simple-schema/simple-schema.js:826:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at [object Object].SimpleSchema.getDefinition (packages/aldeed:simple-schema/simple-schema.js:824:1)
    at checkObj (packages/aldeed:simple-schema/simple-schema-validation.js:217:1)
    at packages/aldeed:simple-schema/simple-schema-validation.js:262:1
    at Array.forEach (native)
<i>

Looks like i18n can't find the json translation files, even the default english one. I tried everything and ended up creating a symbolic link from my en.i18n.json file to my /private directory with  the following code as an ugly workaround:
<pre>
if Meteor.isServer and process.env.IS_MIRROR
    translation = JSON.parse(Assets.getText('en.i18n.json'))
    __ = (key, options) -> translation[key]
else
    __ = TAPi18n.__

Authors.attachSchema(new SimpleSchema(
    'firstName':
        type: String
        max: 100
        label: -> __('author_firstName_label')
    'lastName':
        type: String
        max: 100
        label: -> __('author_lastName_label')
))
</pre>

Note that <code>TAPi18n.loadTranslations({en: translation})</code> wouldn't work either.

Any idea how to fix that in a nice way?

**Comment by theosp** [comment]
Hi,

This should be fixed in v1.5.

Please checkout v1.5 branch to your /packages directory and let me know if it works for you.

Thanks,
-Daniel
[Meteor Developer](http://www.meteorspark.com/)

**Comment by laurentpayot** [comment]
I'd love to try and let you know the result, but I'm new to Meteor and I couldn't find documentation on how to install a specific branch of a package. Cloning the repository in /packages directory and checking the v1.5 branch out apparently wasn't the way to do it. Any link to a doc or a tutorial ?

**Comment by laurentpayot** [comment]
I found out how to build locally from source. v1.5rc2 branch fixed this issue. Thanks! :+1:

**Comment by Cammille** [comment]
Hi,

I've the same problem. 
@laurentpayot, can you tell me how to build locally from source ? 

Thanks !
Cammille.

**Comment by theosp** [comment]
FYI, by the end of the week v1.5 will be published.

-Daniel

**Comment by Cammille** [comment]
Thank you for this information ! I will wait for v1.5...

Cammille

**Comment by theosp** [comment]
v1.5.0 published

**Comment by laurentpayot** [comment]
:+1:

**Comment by Cammille** [comment]
Thanks!
