### ISSUE TITLE
Is there a way to use i18n helper in template arguments?

### ISSUE THREAD

**Issue by rijk** [TAPevents/tap-i18n#66]
Hi,

Is there a way to directly leverage the built-in i18n helper (`_`) when passing arguments to another template? Example:

    {{> ionTab title="Profile"}}

**Comment by theosp** [comment]
How about using the value as the input for the helper in the receiving template?

**Comment by rijk** [comment]
I can’t unfortunately; it’s a [package](https://github.com/meteoric/meteor-ionic)..

**Comment by simongroll** [comment]
Hi @rijk 
Any progress on this?

**Comment by theosp** [comment]
Hi,

It's more a limitation of spacebar. I don't think I can't help much.

Please reopen if you think otherwise.

-Daniel

**Comment by simongroll** [comment]
Hi,

I found a way to leverage built-in i18n helper for the 'Back' button in my application (also using Meteoric like @rijk):

*HTML*
```javascript
{{>ionNavBackButton text=backButtonText path="index"}}
```

*Router*
```javascript
  this.route('routeName', {
    data: {
      backButtonText: function() {
        return TAPi18n.__("back");
      }
    }
  });
```

This will reactively translate text when language is changed.

**Comment by rijk** [comment]
Very cool!

**Comment by nazarposhta** [comment]
what about {{pathFor 'name_of_router'}} - how I can put that parameter in translation text?
