### ISSUE TITLE
Dot inside key names?

### ISSUE THREAD

**Issue by SachaG** [TAPevents/tap-i18n#69]
Are you not supposed to use key names with dot inside them? Like:

```js
{
"foo.bar": "Hello World"
}
```

I'm not quite sure if the issue is coming from there, but apparently that doesn't work?

**Comment by theosp** [comment]
Don't have time to check at the moment, so I might be wrong.

{_ "foo.bar"}

Will be looked under {foo: {bar: "Hello World"}}, and not under "foo.bar".

-Daniel

**Comment by SachaG** [comment]
Oh ok, that makes sense actually! Good to know :)

**Comment by donwojtallo** [comment]
Can I escape dot in key name? I want to translate sentences like "Hello, my name is Bob."

**Comment by hitchcott** [comment]
@donwojtallo it's probably best practice to use something like:

{
  "hello_my_name_is_bob" : "Hello, My name is Bob."
}
