### ISSUE TITLE
Is there a known issue with TAPi18n.__(msg, opt) in a package?

### ISSUE THREAD

**Issue by martinhbramwell** [TAPevents/tap-i18n#73]
I have successfully implemented multi-language behaviour in templates in my app and in a package.  I have also successfully implemented multi-language behaviour with TAPi18n.__(msg, opt) in my app.  

Unfortunately it does not seem to work in a package.  I have tried repeatedly to follow the documentation about it, but I think I am misunderstanding something.

Is this a known problem?

Is there a working example available somewhere?

Thanks

**Comment by theosp** [comment]
Hi,

For packages you shouldn't use: `TAPi18n.__` but `__`.

Read: 
https://github.com/TAPevents/tap-i18n#package-level-tap-i18n-functions

And:
Read https://github.com/TAPevents/tap-i18n#tap-i18n-two-work-modes

-Daniel

**Comment by martinhbramwell** [comment]
That's perfect, thank you.

I did in fact follow exactly that documentation, but did not realize that it meant that the `TAPi18n.` prefix **must** be removed.

Perhaps the docs should state explicitly : 
      "Inside packages you cannot use: `TAPi18n.__`  Use `__.` instead."
