### ISSUE TITLE
My package switches my app to English until I respecify the language to use.

### ISSUE THREAD

**Issue by martinhbramwell** [TAPevents/tap-i18n#74]
This may again be me misreading your docs.  I don't know.

I have not seen how to make my package respect the current language setting of the containing application.  So -- I can navigate through my app in say, Spanish, but when I open a page generated by my package it reverts all subsequent navigation to English.  If I select Spanish again when I am within pages from my package all subsequent navigation continues in Spanish.

Do you need more details to understand what I have done wrong?

**Comment by theosp** [comment]
Without seeing a code example I can't tell what went wrong.
