### ISSUE TITLE
ETA of 1.5 release?

### ISSUE THREAD

**Issue by alexcorre** [TAPevents/tap-i18n#75]
want to use your library but having a lot of trouble since pre `Meteor.startup()` translations are not yet available. 

I see there is a fix for this (issue #56) in v1.5  When do you think itll be released?

**Comment by theosp** [comment]
Hi,

The only reason it wasn't released already is a reported regression related
to use of i18next.addRule() in the application level, I am not sure when
I'll have time to give that issue the full attention it requires.

If you don't use the above it should be safe to use v1.5 (clone it to your
/packages dir).

-Daniel

**Comment by alexcorre** [comment]
thanks @theosp should i use `v1.5` or `v1.5-rc2` branch?

**Comment by theosp** [comment]
rc2 .
