### ISSUE TITLE
question about default language delivery to client

### ISSUE THREAD

**Issue by alexcorre** [TAPevents/tap-i18n#76]
I wanted some clarification on this line from the README: `You probably want to show a loading indicator until the language is ready (as shown in the example), otherwise the templates in your projects will be in English until the language will be ready` 

Does this mean that the english strings file is delivered to the client as part of the client js bundle? If so can you point me to where in the build its being included?  If not how would english language be shown before a language file is delivered?

**Comment by theosp** [comment]
https://github.com/TAPevents/tap-i18n/blob/master/lib/plugin/compilers/i18n.json.coffee#L69-L78

-Daniel
