### ISSUE TITLE
Language tags: - vs _

### ISSUE THREAD

**Issue by SachaG** [TAPevents/tap-i18n#78]
Does tap-i18n also support underscores in language names? (i.e. `pt_BR`)

I'm asking because it looks like this is the syntax that Transifex uses. rather than dashes (`pt-BR`).

**Comment by theosp** [comment]
Hi Sacha,

Underscores tagging aren't supported with tap:i18n, which follows
http://en.wikipedia.org/wiki/IETF_language_tag (or at-least a good enough
subset of it to avoid issues from esoteric edge cases, so far, the standard
is way to big).

Have a good week,
-Daniel

**Comment by SachaG** [comment]
OK, makes sense. It looks like we might use https://lingohub.com instead of Transifex anyway :)
