### ISSUE TITLE
ReferenceError: TAPi18n is not defined, Error: No such function: _

### ISSUE THREAD

**Issue by jazzdragon** [TAPevents/tap-i18n#79]
Hi,
I've seen 3 closed similar issues, but it seems like you fixed them and they're closed.
However, I just added your package to my meteor project, and I'm getting these errors.
My json files are in /lang.
The package seems to be working perfectly though, just these errors being thrown.
Let me know what further info you need from me.
Thanks!
![screen shot 2015-06-11 at 7 20 12 am](https://cloud.githubusercontent.com/assets/5546798/8107932/634fdeea-100a-11e5-91e3-85907aa62710.png)

**Comment by jazzdragon** [comment]
Oh and the error appears only on the client.

**Comment by theosp** [comment]
If you still experience the bug please reproduce on a github repo and share here.

Thanks,
-Daniel
