### ISSUE TITLE
package-tap.i18n mandatory?

### ISSUE THREAD

**Issue by SachaG** [TAPevents/tap-i18n#80]
The documentation makes it sound like having a `package-tap.i18n` file is mandatory, but it seems like if it's missing tap-i18n will just fall back to defaults? Or did I get this wrong?

**Comment by theosp** [comment]
Hi Sacha,

I rely on the existence of package-tap.i18n as a mean to determine the templates that belong to a package (that's why you must load it before the template). Therefore bugs might occur without adding it to package.js.

-Daniel
