### ISSUE TITLE
Empty object json files causes error

### ISSUE THREAD

**Issue by SachaG** [TAPevents/tap-i18n#81]
I'm working with [LingoHub](http://lingohub.com) to manage translations, and one of the things it does is generate empty placeholder translation files. 

The problem is that those files contain `{ }`, and apparently that triggers an error with tap:i18n's parser:

``` js
While building package telescope:getting-started:
   /Users/sacha/Dev/Telescope/packages/telescope-getting-started/i18n/en.i18n.json: Can't load
   `/Users/sacha/Dev/Telescope/packages/telescope-getting-started/i18n/en.i18n.json' JSON
   packages/tap-i18n-compiler/lib/plugin/helpers/load_json.coffee:25:19: Can't load
   `/Users/sacha/Dev/Telescope/packages/telescope-getting-started/i18n/en.i18n.json' JSON (compiling i18n/en.i18n.json)
   at Object._.extend.loadJSON (packages/tap-i18n-compiler/lib/plugin/helpers/load_json.coffee:25:19)
   at Package (packages/tap-i18n-compiler/lib/plugin/compilers/i18n.json.coffee:23:26)
```

I'll make sure there are no empty json objects for now, but it'd be great if tap:i18n could just ignore empty objects and move on to the next file without throwing an error.

**Comment by SachaG** [comment]
Oh and I should also mention that this is only an issue with empty objects in the source language's files, since they're the only ones loaded on the server.

**Comment by hitchcott** [comment]
I think this is a bug.

If i use `{}` or `{ }` I get the same error, but I i use:

```
{
}
```

The error goes away.

**Comment by theosp** [comment]
Couldn't reproduce. I tend to suspect it's an issue with different versions of node.

As the code is very simple: https://github.com/TAPevents/tap-i18n/blob/master/lib/plugin/helpers/load_json.coffee#L18

-Daniel

**Comment by hitchcott** [comment]
Something to do with `JSON.minify` -- isn't that a redundant step (why not just `JSON.parse((fs.readFileSync(file_path, "utf8"))`?

**Comment by theosp** [comment]
Need to understand what is the cause, which function in particular fails for some version of node but is ok for others, then we can implement a fix/workaround.

**Comment by javascriptlove** [comment]
Having the same issue with ```{}```, on Mac, Meteor 1.2.1

```
   blabla/i18n/en.i18n.json: Can't load `blabla/i18n/en.i18n.json' JSON
   <runJavaScript-157>:293:13: Can't load `blabla/i18n/en.i18n.json' JSON (compiling i18n/en.i18n.json)
   at Object._.extend.loadJSON (<runJavaScript-157>:293:13)
   at Package (<runJavaScript-157>:622:26)
```

**Comment by javascriptlove** [comment]
Just tried running ```JSON.minify('{}')``` and it returns an empty string, which is of course not a valid JSON
