### ISSUE TITLE
How to access every entry in a loop

### ISSUE THREAD

**Issue by Fen747** [TAPevents/tap-i18n#84]
Hi!

I'm looking for the best way to create a participative translation tool on my app. For it, I've been using TAP-i18n, which is really great. But I'd need to be able to loop through my keys to duplicate the JSON in new languages, allowing the website users to help translating the tools my app propose.

The problem is that I don't figure out how to programmatically access every key / value in a loop. And without a loop, I'd have to add manualy each entry, which would be really a problem as the app content in growing big and fast.

Any hint / help about that ?

Thanks you

David

**Comment by Kolorbon** [comment]
+1, I also need a way to get all keys + values (the whole object for a selected language), because of SimpleSchema messages and labels.

**Comment by Fen747** [comment]
I found out that you can access it with jquery.ajax :)
