### ISSUE TITLE
setLanguage() does not work properly?

### ISSUE THREAD

**Issue by obiwarn** [TAPevents/tap-i18n#86]
i have quite a large project with many lang files.

when I set the lang on Meteor.startup it does not switch lang. it seems like the files havent been loaded yet.

however, when i call it delayed (e.g. setTimeout(setLang, 1)) it works.

**Comment by obiwarn** [comment]
is there some lazy loading of translation files?

whenever I reload the entire page, I have to use a setTimeout() delay for setLanguage().

**Comment by nate331** [comment]
I experience the same.

**Comment by mzygmunt** [comment]
The same
