### ISSUE TITLE
Using custom language codes

### ISSUE THREAD

**Issue by min2sia** [TAPevents/tap-i18n#87]
I have found that it is possible to use TAPi18n with custom non-existent language codes, like "en-AA", "en-AB", etc. as long as the code format satisfies the validation regexp.

I would like to (ab)use this for my own purposes both with TAPi18n and especially TAPi18n-db as it would save me quite a lot of time. My use case is: I need to publish publications, which not only come in several languages, but also in several editions. Instead of building separate functionality of edition switching, I would rather create a new language variant for each edition, e.g. "[en-AA, en-AB.. en-ZZ], fr-AA", etc. and instantly get all the needed functionality.

Only one small piece is missing: I need a way to change language name and description for my custom language codes which are displayed on TAPi18n-ui controls. Now it displays only codes ("en-AA") while I would need to change it to something like "English 2015 edition".

In my app at runtime I can see two objects `TAPi18n.language_names` and `TAPi18n.languages_names`, where language descriptions are stored and can change their contents from my code, but just can't figure out how to make these display on TAPi18n-ui controls. 
Is it possible at all?

Thanks!

**Comment by theosp** [comment]
Hi,

Very interesting use case.

Without changing tap:i18n/-ui you won't be able to achieve what you want, you need some way to make tap-i18n-ui aware of languages names changes (make getLanguages() reactive resource).

Another much simpler approach, but might not fit to your use case is to add the versions to this file: https://github.com/TAPevents/tap-i18n/blob/43362c8082ecc15edd57a2594f1460569a5b67c5/lib/plugin/etc/language_names.js .

-Daniel

**Comment by min2sia** [comment]
Hi Daniel,

Thanks for your reply!

Actually, I don't need this to be reactive as creation of a new language file would not happen frequently. Application restart is acceptable in these cases. 

Would it be possible to modify 'TAPi18n.language_names' or 'TAPi18n.languages_names' somewhere at `Meteor.startup()` before TAPi18n-ui loads or force TAPi18n-ui reload somehow?

P.S. I also thought of modifying the `language_names.js` file. I guess I will have to take this approach if no better solution can be found.

--
Best regards,
Mindaugas

**Comment by mekhyl** [comment]
Here's what I did and it works for me:
```
Template.i18n_dropdown_semantic.rendered = function() {
   // Give a label to fr-CA (not defined by default in tap-i18n).
   $('option[value=fr-CA]').html('Français (Canada)');
   $('select.dropdown').dropdown();
}
```
