### ISSUE TITLE
TAPi18n.loadTranslations on server does not push the changes to the client

### ISSUE THREAD

**Issue by lowi** [TAPevents/tap-i18n#88]
Is it normal?

**Comment by theosp** [comment]
Yes,

loadTranslations must be called in a code common to both server and client
to affect the two.

-Daniel

**Comment by lowi** [comment]
Any suggestion so I could code such a feature?

**Comment by theosp** [comment]
Perhaps tap:i18n-db fits better to your usecase.

-Daniel

**Comment by lowi** [comment]
Perhaps... I plan to use tap:i18n-db to translate the dynamic content (user generated) of collections to several languages, but for static content I think loading from a json file is the best.
