### ISSUE TITLE
tap-i18n and cordova, it's unstable to display language.

### ISSUE THREAD

**Issue by carrot93** [TAPevents/tap-i18n#91]
First:open the app for the android apk with online, tap-i18n works well.

Second: open the app offline, tap-i18n display default language'en', emm, yes ,tap-i18n need online.

Third: open the app online, tap-i18n still in language'en', not the setLanguage default. It seems the cache not clear?

And idea?

**Comment by theosp** [comment]
A work to make tap:i18n support Cordova properly is needed.

You can see my answer to #93 .

Thanks,
-Daniel

**Comment by theosp** [comment]
Until it will be resolved, use issue #93 to discuss Cordova related issues.
