### ISSUE TITLE
Encoding issue - accentuated characters

### ISSUE THREAD

**Issue by psko** [TAPevents/tap-i18n#94]
Hi,

I have an issue with all my accentuated characters, like if there was an encoding issue.
Modifying `meta charset` doesn't seem to solve the problem.

Here is a sample code:

**sample.html**
```HTML
<head>
    <title>Sample code</title>
    <meta charset="iso-8859-1">
</head>

<template name="sample">
    {{_ "about"}}
</template>
```

**en.i18n.json**
```JSON
{
    "about": "about"
}
```

**fr.i18n.json**
```JSON
{
    "about": "à propos"
}
```

In french, this renders as:
![i18n-issue](https://cloud.githubusercontent.com/assets/6703711/8773128/222c0a92-2ed2-11e5-88a4-1e4c56dd3ee1.jpg)

**Comment by theosp** [comment]
Quick answer, without checking the code.

The i18n files are loaded in the utf-8 encoding if the files are in other
encodings it will lead to the issue as you can see.

-Daniel

**Comment by psko** [comment]
AH I see! I'll change the encoding of my json files then.

I would be great to add it to the documentation, unless I missed it.

**Comment by theosp** [comment]
Mind adding that to the README and sending PR?

Thanks
