### ISSUE TITLE
Helper not available inside angular module

### ISSUE THREAD

**Issue by yanickrochon** [TAPevents/tap-i18n#96]
If I have a template like

```
<div>{{_ "foo"}}</div>
<div ng-app="bar">
  <div>{{_ "bar"}}</div>
</div>
```

What dependency do I need to add to make the helper available?

**Comment by theosp** [comment]
Adding the tap:i18n package should do. Reopen with more details if needed

**Comment by hynese** [comment]
I can confirm that `{{_ "hello"}}` doesn't work in any .ng.html file...

**Comment by damirkusar** [comment]
Me too, this does not work with angular.. and .ng.html files.

**Comment by yobre** [comment]
I'm in the same situation.
Is possible to change the helper " _ " with a filter like [angular-translate](https://github.com/angular-translate/angular-translate)? e.g. {{ "hello" | tapI18n }}

i'm using [angular-meteor](http://www.angular-meteor.com/)

Thanks
