### ISSUE TITLE
Use i18n helper inside another helper. How to?

### ISSUE THREAD

**Issue by anaxyd** [TAPevents/tap-i18n#97]
I am trying to internationalize some helpers, but I am strugging. It seems like its not possible.

Example:

{{> esInput index="courses" class="form-control" placeholder="Search for courses..."}}

How to internationalize the text "Search for courses..."?

**Comment by anaxyd** [comment]
Found that sub-expressions will solve this, which will be available from meteor 1.1.1. Did a walkaround in the meantime:

    {{#if isLanguageTag "nb-NO"}}
      {{> esInput index="courses" class="form-control" placeholder="Søk etter kurs..."}}
    {{else}}
      {{> esInput index="courses" class="form-control" placeholder="Search for courses..."}}
    {{/if}}

With this helper:

    isLanguageTag: function (lang) {
        
        // Returns true if current lang is passed
        return TAPi18n.getLanguage() === lang;
    }

**Comment by flipace** [comment]
I'd also need this - is there any ETA for meteor 1.1.1 ?

**Comment by hitchcott** [comment]
Can't you just do:

```
Templates.myTmpl.helpers
   'searchText': -> TAPi18n.__ 'search_text'
```

@theosp perhaps this needs to be more clearly documented?

**Comment by flipace** [comment]
Yes, that'd be possible, but I'd like to keep the strings directly within the templates.

But for now I think that the helper would probably be the cleanest solution.

**Comment by hitchcott** [comment]
In which case, I think that this is a limitation of handlebars, not TAPi18n (?)

**Comment by flipace** [comment]
Yes, I think that this issue can be closed.
