### ISSUE TITLE
error on empty key TAPi18n.__('');

### ISSUE THREAD

**Issue by illmat** [TAPevents/tap-i18n#99]
In some case I got empty strings from my database.

```
TAPi18n.__(''); or {{_ ''}}
```

returns: "key 'project: (de)' returned an object instead of string."

Of course I could check if the string is empty before calling the function.
But shouldn't this be handled by the package somehow?

**Comment by maxfriedmann** [comment]
yey, ran into the same problem. I would vote for "yes"! :)

:+1:
